"""empty message

Revision ID: 1b607b3e5311
Revises: 5c7a34109dd4
Create Date: 2016-03-17 15:42:19.932200

"""

# revision identifiers, used by Alembic.
revision = '1b607b3e5311'
down_revision = '5c7a34109dd4'

from alembic import op
import sqlalchemy as sa
import us


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    state_table = op.create_table('state',
    sa.Column('abbr', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('abbr')
    )

    op.add_column('ski_area', sa.Column('state', sa.Text(), nullable=True))

    ### end Alembic commands ###

    # Add state data to table
    # for s in us.states.STATES:
    #
    #     # sa.insert('state', abbr=s.abbr, name=s.name)

    states = [{'abbr': s.abbr, 'name': s.name} for s in us.states.STATES]

    op.bulk_insert(state_table, states)



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trail_path', 'trail', ['path'], unique=False)
    op.create_index('idx_ski_area_boundary', 'ski_area', ['boundary'], unique=False)
    op.drop_column('ski_area', 'state')
    op.create_index('idx_lift_path', 'lift', ['path'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.drop_table('state')
    ### end Alembic commands ###
