"""empty message

Revision ID: 4acdd160814c
Revises: efcbf700326c
Create Date: 2016-05-18 00:32:06.164028

"""

# revision identifiers, used by Alembic.
revision = '4acdd160814c'
down_revision = 'efcbf700326c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lift', sa.Column('occupancy', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lift', 'occupancy')
    ### end Alembic commands ###
