"""empty message

Revision ID: 5c7a34109dd4
Revises: None
Create Date: 2016-03-03 11:40:23.848827

"""

# revision identifiers, used by Alembic.
import geoalchemy2

revision = '5c7a34109dd4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('create extension postgis')

    op.create_table('ski_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(), nullable=True),
    sa.Column('inferred', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('ski_area_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('path', geoalchemy2.types.Geometry(), nullable=True),
    sa.ForeignKeyConstraint(['ski_area_id'], ['ski_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('ski_area_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('path', geoalchemy2.types.Geometry(), nullable=True),
    sa.ForeignKeyConstraint(['ski_area_id'], ['ski_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail')
    op.drop_table('lift')
    op.drop_table('user')
    op.drop_table('ski_area')
    ### end Alembic commands ###
